<?php
/**
 * About automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Worker;

use PSX\Schema\Attribute\Description;

#[Description('')]
class About implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('The version of the worker API which is supported')]
    protected ?string $apiVersion = null;
    #[Description('The programming language of this worker')]
    protected ?string $language = null;
    public function setApiVersion(?string $apiVersion) : void
    {
        $this->apiVersion = $apiVersion;
    }
    public function getApiVersion() : ?string
    {
        return $this->apiVersion;
    }
    public function setLanguage(?string $language) : void
    {
        $this->language = $language;
    }
    public function getLanguage() : ?string
    {
        return $this->language;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('apiVersion', $this->apiVersion);
        $record->put('language', $this->language);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
