<?php
/**
 * Execute automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Worker;

use PSX\Schema\Attribute\Description;

#[Description('')]
class Execute implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var \PSX\Record\Record<ExecuteConnection>|null
     */
    #[Description('A map of available connections')]
    protected ?\PSX\Record\Record $connections = null;
    #[Description('')]
    protected ?ExecuteRequest $request = null;
    #[Description('')]
    protected ?ExecuteContext $context = null;
    public function setConnections(?\PSX\Record\Record $connections) : void
    {
        $this->connections = $connections;
    }
    public function getConnections() : ?\PSX\Record\Record
    {
        return $this->connections;
    }
    public function setRequest(?ExecuteRequest $request) : void
    {
        $this->request = $request;
    }
    public function getRequest() : ?ExecuteRequest
    {
        return $this->request;
    }
    public function setContext(?ExecuteContext $context) : void
    {
        $this->context = $context;
    }
    public function getContext() : ?ExecuteContext
    {
        return $this->context;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('connections', $this->connections);
        $record->put('request', $this->request);
        $record->put('context', $this->context);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
