<?php
/**
 * ExecuteContextUser automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Worker;

use PSX\Schema\Attribute\Description;

#[Description('')]
class ExecuteContextUser implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?bool $anonymous = null;
    #[Description('')]
    protected ?int $id = null;
    #[Description('')]
    protected ?string $planId = null;
    #[Description('')]
    protected ?string $name = null;
    #[Description('')]
    protected ?string $email = null;
    #[Description('')]
    protected ?int $points = null;
    public function setAnonymous(?bool $anonymous) : void
    {
        $this->anonymous = $anonymous;
    }
    public function getAnonymous() : ?bool
    {
        return $this->anonymous;
    }
    public function setId(?int $id) : void
    {
        $this->id = $id;
    }
    public function getId() : ?int
    {
        return $this->id;
    }
    public function setPlanId(?string $planId) : void
    {
        $this->planId = $planId;
    }
    public function getPlanId() : ?string
    {
        return $this->planId;
    }
    public function setName(?string $name) : void
    {
        $this->name = $name;
    }
    public function getName() : ?string
    {
        return $this->name;
    }
    public function setEmail(?string $email) : void
    {
        $this->email = $email;
    }
    public function getEmail() : ?string
    {
        return $this->email;
    }
    public function setPoints(?int $points) : void
    {
        $this->points = $points;
    }
    public function getPoints() : ?int
    {
        return $this->points;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('anonymous', $this->anonymous);
        $record->put('id', $this->id);
        $record->put('planId', $this->planId);
        $record->put('name', $this->name);
        $record->put('email', $this->email);
        $record->put('points', $this->points);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
