<?php
/**
 * ResponseEvent automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Worker;

use PSX\Schema\Attribute\Description;

#[Description('')]
class ResponseEvent implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('')]
    protected ?string $eventName = null;
    #[Description('')]
    protected mixed $data = null;
    public function setEventName(?string $eventName): void
    {
        $this->eventName = $eventName;
    }
    public function getEventName(): ?string
    {
        return $this->eventName;
    }
    public function setData(mixed $data): void
    {
        $this->data = $data;
    }
    public function getData(): mixed
    {
        return $this->data;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('eventName', $this->eventName);
        $record->put('data', $this->data);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
