<?php
/**
 * ResponseLog automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Worker;

use PSX\Schema\Attribute\Description;

#[Description('')]
class ResponseLog implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('The log level i.e. error, warning, info, debug')]
    protected ?string $level = null;
    #[Description('')]
    protected ?string $message = null;
    public function setLevel(?string $level): void
    {
        $this->level = $level;
    }
    public function getLevel(): ?string
    {
        return $this->level;
    }
    public function setMessage(?string $message): void
    {
        $this->message = $message;
    }
    public function getMessage(): ?string
    {
        return $this->message;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('level', $this->level);
        $record->put('message', $this->message);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
