<?php
/**
 * Response automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Worker;

use PSX\Schema\Attribute\Description;

#[Description('')]
class Response implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    /**
     * @var array<ResponseEvent>|null
     */
    #[Description('Optional events which are triggered on invocation of this action')]
    protected ?array $events = null;
    /**
     * @var array<ResponseLog>|null
     */
    #[Description('Optional log entries which are generated on invocation of this action')]
    protected ?array $logs = null;
    #[Description('')]
    protected ?int $statusCode = null;
    /**
     * @var \PSX\Record\Record<string>|null
     */
    #[Description('')]
    protected ?\PSX\Record\Record $headers = null;
    #[Description('')]
    protected mixed $body = null;
    /**
     * @param array<ResponseEvent>|null $events
     */
    public function setEvents(?array $events) : void
    {
        $this->events = $events;
    }
    /**
     * @return array<ResponseEvent>|null
     */
    public function getEvents() : ?array
    {
        return $this->events;
    }
    /**
     * @param array<ResponseLog>|null $logs
     */
    public function setLogs(?array $logs) : void
    {
        $this->logs = $logs;
    }
    /**
     * @return array<ResponseLog>|null
     */
    public function getLogs() : ?array
    {
        return $this->logs;
    }
    public function setStatusCode(?int $statusCode) : void
    {
        $this->statusCode = $statusCode;
    }
    public function getStatusCode() : ?int
    {
        return $this->statusCode;
    }
    public function setHeaders(?\PSX\Record\Record $headers) : void
    {
        $this->headers = $headers;
    }
    public function getHeaders() : ?\PSX\Record\Record
    {
        return $this->headers;
    }
    public function setBody(mixed $body) : void
    {
        $this->body = $body;
    }
    public function getBody() : mixed
    {
        return $this->body;
    }
    public function toRecord() : \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('events', $this->events);
        $record->put('logs', $this->logs);
        $record->put('statusCode', $this->statusCode);
        $record->put('headers', $this->headers);
        $record->put('body', $this->body);
        return $record;
    }
    public function jsonSerialize() : object
    {
        return (object) $this->toRecord()->getAll();
    }
}
