<?php
/**
 * Update automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

namespace Fusio\Worker;

use PSX\Schema\Attribute\Description;

#[Description('')]
class Update implements \JsonSerializable, \PSX\Record\RecordableInterface
{
    #[Description('Contains the action worker code')]
    protected ?string $code = null;
    public function setCode(?string $code): void
    {
        $this->code = $code;
    }
    public function getCode(): ?string
    {
        return $this->code;
    }
    public function toRecord(): \PSX\Record\RecordInterface
    {
        /** @var \PSX\Record\Record<mixed> $record */
        $record = new \PSX\Record\Record();
        $record->put('code', $this->code);
        return $record;
    }
    public function jsonSerialize(): object
    {
        return (object) $this->toRecord()->getAll();
    }
}
